export const USER_CREATED = 'USER_CREATED';
export const USER_ACTIVATED = 'USER_ACTIVATED';
export const INACTIVE_USER_SIGNED_IN = 'INACTIVE_USER_SIGNED_IN';

export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_STARTED = 'PASSWORD_RESET_STARTED';

export const EMAIL_RESET_STARTED = 'EMAIL_RESET_STARTED';

export const COURSE_DELETED = 'COURSE_DELETED';
export const COURSE_UPDATED = 'COURSE_UPDATED';
export const COURSE_PROGRESS_RESET = 'COURSE_PROGRESS_RESET';

export const WEEK_CREATED = 'WEEK_CREATED';
export const WEEK_DELETED = 'WEEK_DELETED';
export const WEEK_UPDATED = 'WEEK_UPDATED';

export const STEP_CREATED = 'STEP_CREATED';
export const STEP_UPDATED = 'STEP_UPDATED';
export const STEP_DELETED = 'STEP_DELETED';

export const LECTURE_DELETED = 'LECTURE_DELETED';
export const READING_DELETED = 'READING_DELETED';
export const QUIZ_DELETED = 'QUIZ_DELETED';

export const LECTURE_REQUESTED = 'LECTURE_REQUESTED';
export const READING_REQUESTED = 'READING_REQUESTED';
export const QUIZ_ATTEMPT_SUBMITTED = 'QUIZ_ATTEMPT_SUBMITTED';

export const STUDENT_UNENROLLED = 'STUDENT_UNENROLLED';

export const QUESTION_CREATED = 'QUESTION_CREATED';
export const QUESTION_UPDATED = 'QUESTION_UPDATED';
export const QUESTION_DELETED = 'QUESTION_DELETED';
